<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "management"
 *
 * Auto generated by Extension Builder 2014-04-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'management',
	'description' => 'Management',
	'category' => 'plugin',
	'author' => 'Sergio Catalá',
	'author_email' => 'sergio.catala@audibene.de',
	'author_company' => 'Lukas',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '7.0',
			'fluid' => '7.0',
			'typo3' => '7.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>